### ISSUE TITLE
Undo Button History

### ISSUE THREAD

**Issue by oleteacher** [craciuncezar/Simple-web-image-editor#3]
What a wonder image app, very simple and light weight!

Is there any way to use a history feature with the undo button? For instance: I resize the image and choose effect. If I do not like the effect and undo, all changes are lost not just last one.

Thanks for sharing your work.

**Comment by craciuncezar** [comment]
A little bit of a late response, but i took some time and implement the history feature you suggested 👍 now you can undo and redo as you would normally expect
